test

diff --git a/.github/workflows/ec2-aws-deploy.yml b/.github/workflows/ec2-aws-deploy.yml
--- a/.github/workflows/ec2-aws-deploy.yml
+++ b/.github/workflows/ec2-aws-deploy.yml
@@ -55,16 +55,20 @@ jobs:
       - name: Create DynamoDB Table for Terraform Locking
         run: |
           set -eux
-          TABLE_EXISTS=$(aws dynamodb describe-table --table-name terraform-lock --region eu-central-1 2>&1)
-          if [[ "$TABLE_EXISTS" == *"ResourceNotFoundException"* ]]; then
+          TABLE_EXISTS=$(aws dynamodb describe-table --table-name terraform-lock --region eu-central-1 2>&1 || echo "not found")
+
+          if [[ "$TABLE_EXISTS" == *"not found"* ]]; then
             echo "DynamoDB table doesn't exist, creating now..."
             aws dynamodb create-table \
               --table-name terraform-lock \
               --attribute-definitions AttributeName=LockID,AttributeType=S \
               --key-schema AttributeName=LockID,KeyType=HASH \
               --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
-              --billing-mode PAY_PER_REQUEST --region eu-central-1
-            sleep 10
+              --billing-mode PAY_PER_REQUEST \
+              --region eu-central-1
+            # Wait for DynamoDB table to become available
+            echo "Waiting for DynamoDB table to become available..."
+            aws dynamodb wait table-exists --table-name terraform-lock --region eu-central-1
           else
             echo "DynamoDB table already exists, skipping creation."
           fi
