test

diff --git a/.github/workflows/ec2-aws-deploy.yml b/.github/workflows/ec2-aws-deploy.yml
--- a/.github/workflows/ec2-aws-deploy.yml
+++ b/.github/workflows/ec2-aws-deploy.yml
@@ -32,13 +32,13 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      # Step 5: Build and push Docker images for the backend and frontend
-      - name: Build and Push Docker Images
-        run: |
-          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/flask-terraform-backend:latest ./backend
-          docker push ${{ secrets.DOCKER_USERNAME }}/flask-terraform-backend:latest
-          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/react-terraform-frontend:latest ./frontend
-          docker push ${{ secrets.DOCKER_USERNAME }}/react-terraform-frontend:latest
+      # # Step 5: Build and push Docker images for the backend and frontend
+      # - name: Build and Push Docker Images
+      #   run: |
+      #     docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/flask-terraform-backend:latest ./backend
+      #     docker push ${{ secrets.DOCKER_USERNAME }}/flask-terraform-backend:latest
+      #     docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/react-terraform-frontend:latest ./frontend
+      #     docker push ${{ secrets.DOCKER_USERNAME }}/react-terraform-frontend:latest
 
       # Step 6: Install Terraform
       - name: Install Terraform
@@ -47,11 +47,14 @@ jobs:
           terraform_version: 1.4.0 # Specify the version of Terraform you want
 
       # Step 7: Run Terraform to provision AWS infrastructure
-      - name: Run Terraform
+      - name: Run Terraform to provision AWS infrastructure
         run: |
           cd infrastructure
           terraform init
-          terraform import aws_security_group.app_sg sg-0eb59c9afe84cfe18 || true
+
+          # Optional: Run terraform import only if security group exists
+          terraform import aws_security_group.app_sg sg-0eb59c9afe84cfe18 || echo "Security group not found, creating new one..."
+
           terraform apply -auto-approve
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
